backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "static/img/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Post"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
        required: true
      
      - label: "Autor"
        name: "authors"
        widget: "string" 
        required: true
        default: "mateusrovedaa"

      - label: "Data de publicação"
        name: "date"
        required: false
        widget: "datetime"

      - label: "Tags"
        name: "tags"
        required: false
        widget: "list"

      - label: "Rascunho" 
        name: "draft"
        widget: "boolean" 
        default: true

      - label: "Corpo"
        name: "body"
        widget: "markdown"
  
  - name: "docs"
    label: "Tutoriais"
    folder: "docs/{{category}}/{{slug}}"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"

      - label: "Categoria"
        name: "category"
        required: true
        widget: "string"

      - label: "Rascunho" 
        name: "draft"
        widget: "boolean" 
        default: true

      - label: "Corpo"
        name: "body"
        widget: "markdown"